// ─────────────────────────────────────────────────────────────────────────────
//  SRI SAI TEXCO — Daily Yarn Price Data
//  HOW TO UPDATE: Each morning/evening, update the prices below and change
//  `lastUpdated` to the current date & time. Then deploy (push to GitHub).
// ─────────────────────────────────────────────────────────────────────────────

export type Availability = 'Available' | 'Limited' | 'Enquire';
export type SpinType = 'Ring Spun' | 'OE (Open End)';
export type YarnCategory = 'CWC' | 'KWC' | 'Compact' | 'Slub' | 'OE';

export interface PriceEntry {
  id: string;
  mill: string;
  count: string;          // e.g. "40s", "60s", "10s OE"
  countNum: number;       // numeric value for sorting/filtering
  category: YarnCategory; // CWC | KWC | Compact | Slub | OE
  spinType: SpinType;
  pricePerKg: number;     // today's price in ₹/kg (ex-mill)
  yesterdayPrice: number; // yesterday's price — for ▲/▼ indicator
  packing: string;        // e.g. "50 kg cones"
  moq: string;            // minimum order quantity
  availability: Availability;
  applications: string[];
  notes?: string;
}

// ─── LAST UPDATED — Change this every time you update prices ─────────────────
// Format: ISO 8601 with IST offset (+05:30)
export const lastUpdated = '2026-06-18T08:30:00+05:30';

// ─── PRICE ENTRIES ───────────────────────────────────────────────────────────
// Add or remove rows as needed. Each row = one mill × one count combination.
// Prices shown are indicative ex-mill rates (excluding GST & freight).
export const priceEntries: PriceEntry[] = [

  // ══════════════════════════════════════════════════════════════════════
  // VARDHMAN GROUP — Ludhiana, Punjab
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'vardhman-20s-kwc',
    mill: 'Vardhman',
    count: '20s',
    countNum: 20,
    category: 'KWC',
    spinType: 'Ring Spun',
    pricePerKg: 225,
    yesterdayPrice: 223,
    packing: '30 kg bags / cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Weaving', 'Fabric'],
  },
  {
    id: 'vardhman-30s-cwc',
    mill: 'Vardhman',
    count: '30s',
    countNum: 30,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 248,
    yesterdayPrice: 248,
    packing: '50 kg cones / 30 kg bags',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Weaving', 'Knitting'],
  },
  {
    id: 'vardhman-30s-kwc',
    mill: 'Vardhman',
    count: '30s',
    countNum: 30,
    category: 'KWC',
    spinType: 'Ring Spun',
    pricePerKg: 236,
    yesterdayPrice: 238,
    packing: '30 kg bags / cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Weaving', 'Knitting'],
  },
  {
    id: 'vardhman-40s-cwc',
    mill: 'Vardhman',
    count: '40s',
    countNum: 40,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 270,
    yesterdayPrice: 267,
    packing: '50 kg cones / 30 kg bags',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Knitting', 'Weaving', 'Hosiery'],
    notes: 'Best Seller',
  },
  {
    id: 'vardhman-40s-kwc',
    mill: 'Vardhman',
    count: '40s',
    countNum: 40,
    category: 'KWC',
    spinType: 'Ring Spun',
    pricePerKg: 255,
    yesterdayPrice: 255,
    packing: '30 kg bags / cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Knitting', 'Weaving'],
  },
  {
    id: 'vardhman-40s-compact',
    mill: 'Vardhman',
    count: '40s',
    countNum: 40,
    category: 'Compact',
    spinType: 'Ring Spun',
    pricePerKg: 285,
    yesterdayPrice: 282,
    packing: '50 kg cones',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Premium Knitting', 'Export Fabric'],
  },
  {
    id: 'vardhman-50s-cwc',
    mill: 'Vardhman',
    count: '50s',
    countNum: 50,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 310,
    yesterdayPrice: 308,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Weaving', 'Shirting', 'Export Fabric'],
    notes: 'Popular',
  },
  {
    id: 'vardhman-60s-kwc',
    mill: 'Vardhman',
    count: '60s',
    countNum: 60,
    category: 'KWC',
    spinType: 'Ring Spun',
    pricePerKg: 345,
    yesterdayPrice: 348,
    packing: '30 kg bags / cones',
    moq: '500 kg',
    availability: 'Limited',
    applications: ['Weaving', 'Casual Wear Fabric'],
  },
  {
    id: 'vardhman-slub',
    mill: 'Vardhman',
    count: 'Slub',
    countNum: 40,
    category: 'Slub',
    spinType: 'Ring Spun',
    pricePerKg: 295,
    yesterdayPrice: 295,
    packing: 'As per specification',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Fashion Fabric', 'Ethnic Wear', 'Denim Blends'],
    notes: 'Trending',
  },
  {
    id: 'vardhman-oe-10s',
    mill: 'Vardhman',
    count: '10s OE',
    countNum: 10,
    category: 'OE',
    spinType: 'OE (Open End)',
    pricePerKg: 165,
    yesterdayPrice: 165,
    packing: '5–6 kg cones / 30 kg bags',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Denim', 'Towels', 'Industrial Fabric'],
  },
  {
    id: 'vardhman-oe-16s',
    mill: 'Vardhman',
    count: '16s OE',
    countNum: 16,
    category: 'OE',
    spinType: 'OE (Open End)',
    pricePerKg: 180,
    yesterdayPrice: 178,
    packing: '5–6 kg cones / 30 kg bags',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Hosiery', 'T-shirts', 'Knitting'],
  },
  {
    id: 'vardhman-oe-20s',
    mill: 'Vardhman',
    count: '20s OE',
    countNum: 20,
    category: 'OE',
    spinType: 'OE (Open End)',
    pricePerKg: 192,
    yesterdayPrice: 195,
    packing: '5–6 kg cones / 30 kg bags',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Knitting', 'Hosiery', 'T-shirts'],
  },

  // ══════════════════════════════════════════════════════════════════════
  // TRIDENT GROUP — Barnala, Punjab
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'trident-30s-cwc',
    mill: 'Trident',
    count: '30s',
    countNum: 30,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 252,
    yesterdayPrice: 250,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Weaving', 'Knitting'],
  },
  {
    id: 'trident-40s-cwc',
    mill: 'Trident',
    count: '40s',
    countNum: 40,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 274,
    yesterdayPrice: 270,
    packing: '50 kg cones / 30 kg bags',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Knitting', 'Weaving', 'Hosiery'],
    notes: 'Best Seller',
  },
  {
    id: 'trident-40s-compact',
    mill: 'Trident',
    count: '40s',
    countNum: 40,
    category: 'Compact',
    spinType: 'Ring Spun',
    pricePerKg: 288,
    yesterdayPrice: 285,
    packing: '50 kg cones',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Premium Knitting', 'Export Fabric'],
  },
  {
    id: 'trident-41s-cwc',
    mill: 'Trident',
    count: '41s',
    countNum: 41,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 277,
    yesterdayPrice: 273,
    packing: '50 kg cones',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Weaving', 'Fine Fabric'],
  },
  {
    id: 'trident-50s-cwc',
    mill: 'Trident',
    count: '50s',
    countNum: 50,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 315,
    yesterdayPrice: 312,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Weaving', 'Shirting', 'Export Fabric'],
    notes: 'Popular',
  },
  {
    id: 'trident-60s-cwc',
    mill: 'Trident',
    count: '60s',
    countNum: 60,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 375,
    yesterdayPrice: 372,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Shirting', 'Suiting', 'Lawn Fabric'],
    notes: 'High Demand',
  },
  {
    id: 'trident-61s-cwc',
    mill: 'Trident',
    count: '61s',
    countNum: 61,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 378,
    yesterdayPrice: 375,
    packing: '50 kg cones',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Fine Weaving', 'Specialty Fabric'],
  },
  {
    id: 'trident-80s-cwc',
    mill: 'Trident',
    count: '80s',
    countNum: 80,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 465,
    yesterdayPrice: 460,
    packing: '50 kg cones',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Fine Shirting', 'Premium Export', 'Voile'],
  },
  {
    id: 'trident-oe-10s',
    mill: 'Trident',
    count: '10s OE',
    countNum: 10,
    category: 'OE',
    spinType: 'OE (Open End)',
    pricePerKg: 168,
    yesterdayPrice: 168,
    packing: '5–6 kg cones / 30 kg bags',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Denim', 'Towels', 'Industrial Fabric'],
  },
  {
    id: 'trident-oe-20s',
    mill: 'Trident',
    count: '20s OE',
    countNum: 20,
    category: 'OE',
    spinType: 'OE (Open End)',
    pricePerKg: 195,
    yesterdayPrice: 198,
    packing: '5–6 kg cones / 30 kg bags',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Knitting', 'Hosiery'],
  },

  // ══════════════════════════════════════════════════════════════════════
  // SITARAM — India
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'sitaram-10s-kwc',
    mill: 'Sitaram',
    count: '10s',
    countNum: 10,
    category: 'KWC',
    spinType: 'Ring Spun',
    pricePerKg: 172,
    yesterdayPrice: 170,
    packing: '30 kg bags',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Heavy Fabric', 'Denim', 'Canvas'],
  },
  {
    id: 'sitaram-20s-kwc',
    mill: 'Sitaram',
    count: '20s',
    countNum: 20,
    category: 'KWC',
    spinType: 'Ring Spun',
    pricePerKg: 222,
    yesterdayPrice: 220,
    packing: '30 kg bags / cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Weaving', 'Knitting'],
  },
  {
    id: 'sitaram-30s-kwc',
    mill: 'Sitaram',
    count: '30s',
    countNum: 30,
    category: 'KWC',
    spinType: 'Ring Spun',
    pricePerKg: 238,
    yesterdayPrice: 240,
    packing: '30 kg bags / cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Weaving', 'Fabric'],
  },
  {
    id: 'sitaram-40s-cwc',
    mill: 'Sitaram',
    count: '40s',
    countNum: 40,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 268,
    yesterdayPrice: 265,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Knitting', 'Weaving'],
  },
  {
    id: 'sitaram-oe-16s',
    mill: 'Sitaram',
    count: '16s OE',
    countNum: 16,
    category: 'OE',
    spinType: 'OE (Open End)',
    pricePerKg: 176,
    yesterdayPrice: 175,
    packing: '5–6 kg cones',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Hosiery', 'T-shirts', 'Knitting'],
  },

  // ══════════════════════════════════════════════════════════════════════
  // WELSPUN — Gujarat
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'welspun-20s-kwc',
    mill: 'Welspun',
    count: '20s',
    countNum: 20,
    category: 'KWC',
    spinType: 'Ring Spun',
    pricePerKg: 220,
    yesterdayPrice: 218,
    packing: '30 kg bags / cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Towels', 'Home Textiles', 'Weaving'],
  },
  {
    id: 'welspun-30s-cwc',
    mill: 'Welspun',
    count: '30s',
    countNum: 30,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 250,
    yesterdayPrice: 248,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Weaving', 'Knitting', 'Home Textiles'],
  },
  {
    id: 'welspun-40s-cwc',
    mill: 'Welspun',
    count: '40s',
    countNum: 40,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 272,
    yesterdayPrice: 272,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Knitting', 'Weaving', 'Hosiery'],
  },
  {
    id: 'welspun-oe-10s',
    mill: 'Welspun',
    count: '10s OE',
    countNum: 10,
    category: 'OE',
    spinType: 'OE (Open End)',
    pricePerKg: 163,
    yesterdayPrice: 162,
    packing: '5–6 kg cones / 30 kg bags',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Denim', 'Towels', 'Home Textiles'],
  },
  {
    id: 'welspun-oe-20s',
    mill: 'Welspun',
    count: '20s OE',
    countNum: 20,
    category: 'OE',
    spinType: 'OE (Open End)',
    pricePerKg: 190,
    yesterdayPrice: 192,
    packing: '5–6 kg cones / 30 kg bags',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Hosiery', 'Knitting', 'T-shirts'],
  },

  // ══════════════════════════════════════════════════════════════════════
  // NAHAR GROUP — Punjab
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'nahar-40s-cwc',
    mill: 'Nahar',
    count: '40s',
    countNum: 40,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 265,
    yesterdayPrice: 263,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Knitting', 'Hosiery', 'Weaving'],
  },
  {
    id: 'nahar-50s-cwc',
    mill: 'Nahar',
    count: '50s',
    countNum: 50,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 308,
    yesterdayPrice: 305,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Weaving', 'Shirting'],
  },
  {
    id: 'nahar-60s-cwc',
    mill: 'Nahar',
    count: '60s',
    countNum: 60,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 370,
    yesterdayPrice: 370,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Limited',
    applications: ['Shirting', 'Fine Fabric', 'Export'],
  },
  {
    id: 'nahar-80s-cwc',
    mill: 'Nahar',
    count: '80s',
    countNum: 80,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 460,
    yesterdayPrice: 455,
    packing: '50 kg cones',
    moq: '1 MT',
    availability: 'Enquire',
    applications: ['Fine Shirting', 'Premium Export', 'Voile'],
  },
  {
    id: 'nahar-105s-cwc',
    mill: 'Nahar',
    count: '105s',
    countNum: 105,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 615,
    yesterdayPrice: 610,
    packing: '50 kg cones',
    moq: '1 MT',
    availability: 'Enquire',
    applications: ['Super Fine Fabric', 'Luxury Export', 'High-end Shirting'],
  },

  // ══════════════════════════════════════════════════════════════════════
  // SINTEX — Gujarat
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'sintex-30s-cwc',
    mill: 'Sintex',
    count: '30s',
    countNum: 30,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 246,
    yesterdayPrice: 244,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Weaving', 'Knitting'],
  },
  {
    id: 'sintex-40s-cwc',
    mill: 'Sintex',
    count: '40s',
    countNum: 40,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 266,
    yesterdayPrice: 264,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Knitting', 'Weaving'],
  },
  {
    id: 'sintex-50s-cwc',
    mill: 'Sintex',
    count: '50s',
    countNum: 50,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 305,
    yesterdayPrice: 308,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Weaving', 'Shirting', 'Fine Fabric'],
  },
  {
    id: 'sintex-120s-cwc',
    mill: 'Sintex',
    count: '120s',
    countNum: 120,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 740,
    yesterdayPrice: 730,
    packing: '50 kg cones',
    moq: '1 MT',
    availability: 'Enquire',
    applications: ['Ultra Fine Fabric', 'Luxury Export', 'Premium Shirting'],
  },
];

// ── GHCL TEXTILES — Paravai & Manaparai, Tamil Nadu ─────────────────────────
// (Append to the array above by adding entries here when needed)
// Already added inline below:
export const ghclEntries: PriceEntry[] = [
  {
    id: 'ghcl-30s-cwc',
    mill: 'GHCL',
    count: '30s',
    countNum: 30,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 245,
    yesterdayPrice: 243,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Weaving', 'Knitting'],
  },
  {
    id: 'ghcl-40s-cwc',
    mill: 'GHCL',
    count: '40s',
    countNum: 40,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 268,
    yesterdayPrice: 266,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Knitting', 'Weaving', 'Hosiery'],
    notes: 'Best Seller',
  },
  {
    id: 'ghcl-40s-compact',
    mill: 'GHCL',
    count: '40s',
    countNum: 40,
    category: 'Compact',
    spinType: 'Ring Spun',
    pricePerKg: 282,
    yesterdayPrice: 280,
    packing: '50 kg cones',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Premium Knitting', 'Export Fabric'],
  },
  {
    id: 'ghcl-50s-cwc',
    mill: 'GHCL',
    count: '50s',
    countNum: 50,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 305,
    yesterdayPrice: 303,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Weaving', 'Shirting', 'Export Fabric'],
    notes: 'Popular',
  },
  {
    id: 'ghcl-60s-cwc',
    mill: 'GHCL',
    count: '60s',
    countNum: 60,
    category: 'CWC',
    spinType: 'Ring Spun',
    pricePerKg: 368,
    yesterdayPrice: 365,
    packing: '50 kg cones',
    moq: '500 kg',
    availability: 'Available',
    applications: ['Fine Shirting', 'Lawn Fabric', 'Export'],
    notes: 'High Demand',
  },
  {
    id: 'ghcl-60s-compact',
    mill: 'GHCL',
    count: '60s',
    countNum: 60,
    category: 'Compact',
    spinType: 'Ring Spun',
    pricePerKg: 382,
    yesterdayPrice: 378,
    packing: '50 kg cones',
    moq: '1 MT',
    availability: 'Available',
    applications: ['Premium Export', 'Fine Shirting'],
  },
];

// Merge GHCL into main list
priceEntries.push(...ghclEntries);


// ─── HELPER: get unique mills ────────────────────────────────────────────────────
export const allMills = Array.from(new Set(priceEntries.map((e) => e.mill))).sort();

// ─── HELPER: get unique counts ───────────────────────────────────────────────────
export const allCounts = Array.from(new Set(priceEntries.map((e) => e.count))).sort(
  (a, b) => {
    const na = parseInt(a) || 0;
    const nb = parseInt(b) || 0;
    return na - nb;
  },
);

// ─── HELPER: get price change info ───────────────────────────────────────────
export function getPriceChange(entry: PriceEntry): {
  diff: number;
  pct: string;
  direction: 'up' | 'down' | 'flat';
} {
  const diff = entry.pricePerKg - entry.yesterdayPrice;
  const pct = ((diff / entry.yesterdayPrice) * 100).toFixed(2);
  return {
    diff,
    pct,
    direction: diff > 0 ? 'up' : diff < 0 ? 'down' : 'flat',
  };
}
